version: '3.7'

services:
  app:
    build: .
    image: rails:202303
    container_name: rails
    restart: always
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    environment:
      RAILS_RELATIVE_URL_ROOT: /rails
      RAILS_ENV: "development"
      DB_USER_NAME: "info"
      DB_PASSWORD: "password"
      DB_HOST: "postgres"
      EDITOR: "vim"
    volumes:
      - ./:/var/www/app
      - ~/.ssh:/root/.ssh
      - root-data:/root # .bash_profileなどを永続化
      - vendor-data:/var/www/app/vendor/
    networks: # nginxを基準にcontainerとネットワーク共有
      nginx_default:
    command: >
      bash -c "rm -f tmp/pids/server.pid &&
      touch /root/.bash_profile &&
      bundle install --path vendor/bundler &&
      bin/rails db:create db:migrate db:seed &&
      bundle exec rails server"

volumes:
  root-data:
    driver: local
  vendor-data:
    driver: local

networks:
  nginx_default:
    external: true
