default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: info
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myapp

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: myapp
